### ISSUE TITLE
Query: Modifying node.value in AST

### ISSUE THREAD

**Issue by VamKram** [kwonoj/woodpile#10]
Hello Maintainers,

I am currently working on a feature that requires manipulation of the AST, specifically modifying the node.value of certain nodes. I've scoured the documentation and GitHub issues, but I haven't found a clear answer on the best way to go about this.

Could anyone provide guidance or point me to the relevant documentation/resources that describe how to modify the node.value?

I wanna printSync the modified code
thx
const { visit } = require('woodpile');
const { readFileSync } = require('fs');
const { parseSync, printSync } = require('@swc/core');

let str = readFileSync("./test.tsx", "utf-8")
const ast = parseSync(readFileSync("./test.tsx", "utf-8"), {
    tsx: true,
    syntax: 'typescript',
    decorators: true
});

const res = visit(ast, {
    visitWithPath: {
        visitLit: (node, path) => {
            node.value = "test"
        },
    },
});

its not work
const code = printSync(ast)
console.log("code:", str);

**Comment by VamKram** [comment]
> https://github.com/kwonoj/woodpile#usage

apologize, my example was not complete. was The issue that I did not return the node?
but
```javascript
const { visit } = require('woodpile');
const { readFileSync, writeFileSync } = require('fs');
const { parseSync, printSync } = require('@swc/core');

const ast = parseSync(readFileSync("./test.tsx", "utf-8"), {
    tsx: true,
    syntax: 'typescript',
    decorators: true
});

visit(ast, {
    visit: {
        visitLit: (node, self) => {
            node.value = "test";
            return node
        },
    },
});
```

the AST still has not changed
there is minimum reproduction method

https://codesandbox.io/p/sandbox/thirsty-stonebraker-3zy7w2?file=%2Findex.js%3A32%2C27

**Comment by iantanwx** [comment]
@kwonoj this issue persists and seems inconsistent with the Rust visitor API, which allows mutation of the AST.

It seems that this is not the case here, because `serde_wasm_bindgen::from_value` creates a copy of `JsValue`, and [`call_visit_mut_inner`](https://github.com/kwonoj/woodpile/blob/main/packages/woodpile/src/visit_mut_macros_helper.rs#L50) just changes the address of the copy, which never gets returned to the JS side.
