### ISSUE TITLE
Woodpile bindings don't work with next.js

### ISSUE THREAD

**Issue by iantanwx** [kwonoj/woodpile#11]
When importing woodpile into a next.js route (^14), the route can't be called.

Reproduction: https://github.com/iantanwx/woodpile-repro

It looks like the wasm target doesn't work. Is there any work around I can try?

**Comment by kwonoj** [comment]
1. I don't see woodpile's imported in the repro

2. If it doesn't work I presume wasm import have some config issues with next.js. this package useing wasm-pack straightforwardly without any config, so I expect you may try to find next.js to allow to import wasm binaries.

**Comment by kwonoj** [comment]
> swc/wasm-web works fine

I guess this is the answer - currently woodpile is targeting node.js only. If you have a PR targets web both, happy to add it. Should only require some changes in pkg.json exports field with build script adjustments.

**Comment by iantanwx** [comment]
@kwonoj thanks! I'll work on adding a PR for that. Thanks for your help.
