### ISSUE TITLE
Runs 125x slower than using `@swc/core/Visitor.js`

### ISSUE THREAD

**Issue by swwind** [kwonoj/woodpile#15]
I have written a [simple program](https://pastebin.com/XR8XQHiG) to compare the execution efficiency of using `@swc/core/Visitor.js` versus `woodpile`. The results show that `woodpile` is nearly 125 times slower on my machine (swc: ~20ms, woodpile: ~2500ms). I believe the frequent context switching between WASM and JS results in overhead that outweighs any potential performance gains.

I am uncertain about the practical application of this project although it says we focus on correctness over performance. However, I noticed the deprecation tag on @swc/core/Visitor.js and saw an [RFC regarding the deprecation of the JS visitor](https://github.com/swc-project/swc/discussions/7673). If this means the SWC project intends to completely remove the Visitor.js code and expects users to perform `traverse` to a **JS object** using **JS** in a similar manner to this project, I am strongly opposed to this direction.

Additionally, I think users might not necessarily use Visitor.js solely for implementing transformers and plugins. For example, in my performance comparison program, I only want to use SWC to parse a js codebase and identify all identifiers for further use. The current Visitor.js perfectly satisfies this requirement without needing to write a separate Rust code and compile it into WASM. This seems like overkill for such a task.

**Comment by kwonoj** [comment]
-  Doc clearly mentions there are perf penalty and this is mostly useful for `prototyping` or `duck typing` for those reasons.

- 
> SWC project intends to completely remove the Visitor.js code and expects users to perform traverse to a JS object using JS in a similar manner to this project

No, swc/core recommends to migrate into wasm plugins. There are no plans to recommend to user to use JS to write plugins.

> Additionally, I think users might not necessarily use Visitor.js solely for implementing transformers and plugins. For example, in my performance comparison program, I only want to use SWC to parse a js codebase and identify all identifiers for further use. The current Visitor.js perfectly satisfies this requirement without needing to write a separate Rust code and compile it into WASM.

This is not related with this project, as this is a 3rd party pkg not affiliated to the swc/core itself. However, to add some note that `I only want to use SWC to parse a js codebase and identify all identifiers for further use.` if you're doing this in js context, that involves heavy perf penalty to pass ast in between rust and v8.

**Comment by swwind** [comment]
Ok, if I get it right, this project is not intended to take place of that `@swc/core/visitor`, and that RFC is just for deprecating js-visitor **plugins** but not js-visitor itself.

That would be my misunderstanding, sorry for that.

**Comment by kwonoj** [comment]
> deprecating js-visitor plugins but not js-visitor itself.

No, both will be deprecated but this package is not related with deprecation plan.
