### ISSUE TITLE
Cooooool. Future plans for this library.

### ISSUE THREAD

**Issue by hg-pyun** [kwonoj/woodpile#9]
Hi, I was wondering if I should implement the Visitor implementation myself and found this library. It's still useful now, but I think it'll be good if the function is added. Do you happen to have a long-term milestone? 🍻

**Comment by kwonoj** [comment]
This library aims to provide parity to rust api's visitor macros. Which means if there are missing visitor calls, it may be added and should be straightforward. Other than those, do not plan to implement its own features.
